blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community about the UNICORN Bybit WebSocket API and ask general questions.
  - name: UNICORN Bybit WebSocket API Discussions
    url: https://github.com/LUCIT-Systems-and-Development/unicorn-bybit-websocket-api/discussions
    about: Ask general questions.
  - name: UNICORN Bybit WebSocket API documentation
    url: https://unicorn-bybit-websocket-api.docs.lucit.tech/
    about: The complete UNICORN Bybit WebSocket API documentation.
  - name: Get Professional and Fast Support
    url: https://www.lucit.tech/get-support.html
    about: Contact the LUCIT Development Team.
  - name: Get a UNICORN Trading Suite License
    url: https://shop.lucit.services/software/unicorn-trading-suite
    about: LUCIT Online Shop