name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_python_3_7:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

  test_python_3_8:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

  test_python_3_9:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

  test_python_3_10:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

  test_python_3_11:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

  test_python_3_12:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls

    - name: Unit test
      env:
          LUCIT_API_SECRET: ${{ secrets.LUCIT_API_SECRET }}
          LUCIT_LICENSE_TOKEN: ${{ secrets.LUCIT_LICENSE_TOKEN }}
      run: coverage run --source unicorn_bybit_websocket_api unittest_bybit_websocket_api.py

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: LUCIT-Systems-and-Development/unicorn-bybit-websocket-api
